### ISSUE TITLE
Failed to build on Mac

### ISSUE THREAD

**Issue by ytfei** [darkk/redsocks#57] opened 2015-04-07 05:01 UTC
When built on Mac, I got `.depend:1: *** missing separator.  Stop.`

`make --version`

```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by darkk** [comment] 2015-04-08 09:03
What C compiler do you use? Only `gcc` is supported for `.depend` file generation.

**Comment by ytfei** [comment] 2015-04-20 03:29
```
redsocks$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

what should i do if wish to build redsocks on Mac? install gcc or simply update the Makefile ? Sorry i'm not familiar with C

**Comment by jondb** [comment] 2015-09-17 17:28
@darkk the issue is with the command `echo -n`. 

## On Ubuntu, it works

    $ sh -c 'echo -n bob'
    bob$
    $ ls -al /bin/sh
    lrwxrwxrwx 1 root root 4 Apr 17  2014 /bin/sh -> dash

## On OSX, it doesn't work with sh

    $ sh -c 'echo -n bob'
    -n bob
    $ 
    $ sh --version
    GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
    Copyright (C) 2007 Free Software Foundation, Inc.
    $

But it does with bash.

## The fix

Set the shell in the Makefile. Add this to the top:

    SHELL := /bin/bash

example:

     DEPS := .depend
     OUT := redsocks
     VERSION := 0.4
    +SHELL := /bin/bash

     LIBS := -levent
     CFLAGS += -g -O2

**Comment by darkk** [comment] 2018-02-01 19:46
I have no permanent root access to machines running MacOSX to test and develop for this platform. Was v0.4 ever working on MacOSX? If it was, please contribute documentation with working MacOSX firewall configuration guidelines.

Also, I'm closing this issue in favor of #75 that tracks current MacOSX support status.

**Closed by darkk** 2018-02-01 19:46 UTC
