### ISSUE TITLE
I use redirector=pf on Mac OS X,but failed

### ISSUE THREAD

**Issue by tony1016** [darkk/redsocks#73] opened 2016-01-14 05:48 UTC
I install rednecks from homebrew.And config `redirector = pf ;`  because of os x 10.10 using pfctl instead of ipfw.But it failed:

```
file parsing error at line 6: invalid `redirector` set
file parsing error at line 6: section->on exit failed
```

**Comment by saltydizz** [comment] 2016-05-10 14:49
I had this problem here, Mac use pfctl, maybe it's a pf wrapper, can redsocks support it?

**Comment by unger1984** [comment] 2017-11-27 15:19
+1. 
Did anyone decide problem with start redsocks on Mac OS ?

**Comment by darkk** [comment] 2018-02-01 19:26
I have no permanent root access to machines running MacOSX to test and develop for this platform. Was v0.4 ever working on MacOSX? If it was, can you please contribute documentation with working MacOSX firewall configuration guidelines?

Also, I'm closing this as duplicate of #63.

**Closed by darkk** 2018-02-01 19:26 UTC

**Comment by mohsenasm** [comment] 2023-10-17 11:14
These links may help:
+ https://serverfault.com/questions/709369/pf-mac-os-x-rule-to-redirect-all-traffic-to-a-specific-ip-port
+ https://gist.github.com/flackend/7c999c943ab46f4bfe34
+ https://lucumr.pocoo.org/2013/1/6/osx-wifi-proxy/

I haven't tried to get it working yet.
