### ISSUE TITLE
Use the redudp service failed to resolve DNS

### ISSUE THREAD

**Issue by qiuzi** [darkk/redsocks#72] opened 2015-12-18 16:02 UTC
1450454281.322590 redudp.c:551 redudp_first_pkt_from_client(...) [192.168.1.122:59922->8.8.8.8:53]: got 1st packet from client
1450454281.322750 redudp.c:479 redudp_relay_connected(...) [192.168.1.122:59922->8.8.8.8:53]: via 127.0.0.1:8888
1450454281.323970 redudp.c:435 redudp_read_auth_methods(...) [192.168.1.122:59922->8.8.8.8:53]: <trace>
1450454281.326110 redudp.c:334 redudp_read_assoc_reply(...) [192.168.1.122:59922->8.8.8.8:53]: <trace>
1450454281.326370 redudp.c:317 redudp_flush_queue(...) [192.168.1.122:59922->8.8.8.8:53]: Starting UDP relay
1450454281.326790 redudp.c:505 redudp_relay_error(...) [192.168.1.122:59922->8.8.8.8:53]: redudp_relay_error
1450454281.326910 redudp.c:218 redudp_drop_client(...) [192.168.1.122:59922->8.8.8.8:53]: Dropping...

SOCKS5 supports UDP

**Comment by darkk** [comment] 2018-02-01 20:27
> redudp_relay_error

I'm not sure if that implementation of Socks5 supports UDP. Probably, packet capture is required to debug issue.
I'm also unsure if the issue is still relevant, so I'm closing it. Please, reopen if it is.

**Closed by darkk** 2018-02-01 20:27 UTC
